#ifndef SIMPLELOOPER_H
#define SIMPLELOOPER_H

#include "TFile.h"
#include "TTree.h"
#include "TH1.h"
#include "TProfile.h"
#include <vector>
#include <fstream>
#include "Math/LorentzVector.h"

Int_t   nbgen_    ;
Int_t   ncgen_    ;
Int_t   njets_    ;
Int_t   njets40_  ;
Int_t   njets50_  ;
Int_t   njets100_ ;
Int_t   ngenjets_ ;
Int_t   njetsfwd_    ;
Int_t   njetsfwd40_  ;
Int_t   njetsfwd50_  ;
Int_t   njetsfwd100_ ;
Int_t   ngenjetsfwd_ ;
Int_t   nels_     ;
Int_t   nmus_     ;
Int_t   nleps_    ;
Int_t   ngenels_  ;
Int_t   ngenmus_  ;
Int_t   ngentaus_ ;
Int_t   ngenleps_ ;
Float_t met_      ;
Float_t dilmass_  ;
Float_t metphi_   ;
Float_t ht_       ;
Float_t jet1pt_   ;
Float_t jet2pt_   ;
Float_t jet3pt_   ;
Float_t jet4pt_   ;
Float_t jet1eta_  ;
Float_t jet2eta_  ;
Float_t jet3eta_  ;
Float_t jet4eta_  ;
Float_t jet1phi_  ;
Float_t jet2phi_  ;
Float_t jet3phi_  ;
Float_t jet4phi_  ;
Float_t jet1genpt_;
Float_t jet2genpt_;
Float_t jet3genpt_;
Float_t jet4genpt_;
Float_t genjetb1pt_   ;
Float_t genjetb2pt_   ;
Float_t genjetb1eta_  ;
Float_t genjetb2eta_  ;
Float_t genjetb1phi_  ;
Float_t genjetb2phi_  ;
Float_t genjetb1recopt_;
Float_t genjetb2recopt_;
Int_t genjetb1tag_;
Int_t genjetb2tag_;
Float_t bjet1pt_  ;
Float_t bjet2pt_  ;
Float_t bjet1eta_ ;
Float_t bjet2eta_ ;
Float_t bjet1phi_ ;
Float_t bjet2phi_ ;
Float_t st_       ;
Float_t stlep_    ;
Float_t genweight_ ;
Float_t xsec_     ;
Int_t   nevents_  ;
Float_t weight_   ;
Int_t   nw_       ;
Int_t   nh_       ;
Int_t   nz_       ;
Int_t   ntop_     ;
Int_t   nb_       ;
Float_t mt_       ;
Float_t mct_      ;
Float_t mbb_      ;
Float_t drbb_     ;
Float_t drbbgen_  ;
Float_t pthgen_   ;
Float_t ptc1gen_  ;
Float_t genlep1pt_  ;
Float_t genlep1eta_ ;
Float_t genb1pt_  ;
Float_t genb1eta_ ;
Float_t genb2pt_  ;
Float_t genb2eta_ ;
Float_t ptbb_     ;
Float_t lep1pt_   ;
Float_t lep1eta_  ;
Float_t lep1phi_  ;
Float_t lep1iso_  ;
Float_t lep1genpt_;
Float_t lep2pt_   ;
Float_t lep2eta_  ;
Float_t lep2phi_  ;
Float_t lep2iso_  ;
Int_t   leptype_  ;
Int_t   mchi_     ;
Int_t   mlsp_     ;
Float_t mwgen_    ;
Float_t mtwgen_   ;
Float_t mttgen_   ;
Float_t ptttgen_  ;
Float_t genmet_   ;
Float_t genmetphi_;
Float_t pujetmet_      ;
Float_t pujetmetphi_   ;
Float_t pujetmt_      ;
Float_t puppimet_      ;
Float_t puppimetphi_   ;
Float_t puppimt_      ;
Float_t phot1pt_   ;
Float_t phot1eta_  ;
Float_t phot1phi_  ;
Float_t phot1iso_  ;
Float_t bgweight_  ;
Int_t   prodcode_  ;

// puppi versions
Int_t   nb_puppi_       ;
Int_t   njets_puppi_    ;
Int_t   njets40_puppi_  ;
Int_t   njets50_puppi_  ;
Int_t   njets100_puppi_ ;
Int_t   njetsfwd_puppi_    ;
Int_t   njetsfwd40_puppi_  ;
Int_t   njetsfwd50_puppi_  ;
Int_t   njetsfwd100_puppi_ ;
Float_t jet1pt_puppi_   ;
Float_t jet2pt_puppi_   ;
Float_t jet3pt_puppi_   ;
Float_t jet4pt_puppi_   ;
Float_t jet1eta_puppi_  ;
Float_t jet2eta_puppi_  ;
Float_t jet3eta_puppi_  ;
Float_t jet4eta_puppi_  ;
Float_t jet1phi_puppi_  ;
Float_t jet2phi_puppi_  ;
Float_t jet3phi_puppi_  ;
Float_t jet4phi_puppi_  ;
Float_t jet1genpt_puppi_;
Float_t jet2genpt_puppi_;
Float_t jet3genpt_puppi_;
Float_t jet4genpt_puppi_;
Float_t bjet1pt_puppi_  ;
Float_t bjet2pt_puppi_  ;
Float_t bjet1eta_puppi_ ;
Float_t bjet2eta_puppi_ ;
Float_t bjet1phi_puppi_ ;
Float_t bjet2phi_puppi_ ;
Float_t mct_puppi_      ;
Float_t mbb_puppi_      ;
Float_t drbb_puppi_     ;
Float_t ptbb_puppi_     ;

#endif
